twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes: ['bootstrap_4_layout.html.twig']

    globals:
      category: '@App\Repository\CategoryRepository'
      shop: '@App\Repository\ShopRepository'
