twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes: ['bootstrap_4_layout.html.twig']

    globals:
      categoryrepo: '@App\Repository\CategoryRepository'
      shoprepo: '@App\Repository\ShopRepository'
      productrepo: '@App\Repository\ProductRepository'
